### ISSUE TITLE
Could you upload the requirements.txt file and your python version?

### ISSUE THREAD

**Issue by setrsw** [Zhangcx19/IJCAI-23-PFedRec#1]

**Comment by xiangxingGuo** [comment]
I ran this code in the following environment: torch 1.12.1, Python 3.10 with CUDA 10.2 and cuDNN 7.6.5, pandas 2.0.3, tensorboardX 2.2, and numpy 1.25.2.

Also, you need "mkdir log" and "mkdir sh_result"

**Comment by setrsw** [comment]
Thanks!

**Comment by Zhangcx19** [comment]
Sorry for the late reply! I have uploaded the requirements.txt and the Python version is 3.7.
Thanks for your attention!

**Comment by cocomoff** [comment]
Thank you for an early discussion on `requirements.txt`.
After @Zhangcx19 updated the file, unfortunately, some libraries seem to depend on the local environment. 

I wrote this message to help this issue for future researchers.
I tested with Python 3.11 with CUDA11 of numpy 1.26.3, pandas 1.3.5, tensorboardX 2.6.2, torch 2.2.2+cu118.

> This version requires a minor modification of `data.py` as from `lambda x: random.sample(x, 198))` to `lambda x: random.sample(list(x), 198))` in L.80 and L.88.

Here, my running results after Epoch 50:

```txt
2024-04-11 05:33:21,071-INFO-Testing phase!
2024-04-11 05:33:22,044-INFO-[Testing Epoch 50] HR = 0.7084, NDCG = 0.4215
2024-04-11 05:33:22,044-INFO---------------------------------------------------------------------------------
2024-04-11 05:33:22,044-INFO-Validating phase!
2024-04-11 05:33:23,060-INFO-[Evluating Epoch 50] HR = 0.7487, NDCG = 0.4617
```
