### ISSUE TITLE
学习率问题

### ISSUE THREAD

**Issue by gsy901** [Zhangcx19/IJCAI-23-PFedRec#2]
为什么更新物品嵌入模块的学习率lr=self.config['lr'] * self.config['num_items'] * self.config['lr_eta'] 
这样的话如果使用ml-100k数据集 学习率lr=13456.000000000002
不会太大吗

**Comment by HuHu246** [comment]
同问

**Comment by Zhangcx19** [comment]
非常感谢对我们工作的关注！

关于为商品嵌入设置较大的学习率，基本思路是终端模型中商品嵌入和评分函数的参数更新频率不同。具体来说，在终端模型的每次训练迭代中，评分函数的更新与数据集中包含的所有样本数量相关，即用户交互过的全部（商品id，评分）；而商品嵌入中每一行参数的更新仅与数据集中的特定样本相关，即用户交互过的特定（商品id，评分）。因此，通过为商品嵌入设置比评分函数更大的学习率有助于缓解商品嵌入模块和评分函数模块参数更新频率存在差异的问题。
